# Generated by Django 4.0.2 on 2022-02-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_articles_options_alter_articles_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=' عنوان دسته بندی')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='categories',
            field=models.ManyToManyField(to='myapp.Category', verbose_name='دسته بندی ها'),
        ),
    ]
