# Generated by Django 4.0.2 on 2022-02-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_options_remove_articles_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='categories',
            field=models.ManyToManyField(to='myapp.Category', verbose_name='دسته بندی ها'),
        ),
    ]
