# Generated by Django 4.0.2 on 2022-02-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_articles_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='categories',
            new_name='category',
        ),
    ]
