# Generated by Django 4.0.2 on 2022-02-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_categories_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(related_name='articlees', to='myapp.Category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟'),
        ),
    ]
