# Generated by Django 4.0.2 on 2022-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='x', upload_to='images', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
